config/routes.rb
Rails.application.routes.draw do
  get "logout" => "sessions#destroy"
  get "login" => "sessions#new"
  post "login" => "sessions#create"

  get 'edit-profile' => 'users#edit'
  delete 'delete' => 'users#destroy'
  patch 'update-profile' => 'users#update'

  resources :articles
  resources :tags, except: %i[show]
  resources :users, only: %i[index show] do
    member do
      patch 'verify' => 'users#verify'
    end
    collection do
      get 'change-password' => 'users#change_password'
      patch 'change-password' => 'users#update_password'
      get 'leaderboard' => 'users#leaderboard'
    end
  end

  get 'contact' => 'static#contact'
  get 'about' => 'static#about'
  get 'faqs' => 'static#faqs'
  get 'privacy' => 'static#privacy'
  root 'static#index'
end

app/models/article.rb
require 'articles_tag'
require 'concerns/articles_validation'

class Article < PermissionModel
  include ActionView::Helpers::SanitizeHelper
  include ArticlesValidation

  alias_method :owner, :author

  def self.search(q=nil, tags: nil, author: nil)
    query = search_by_tags tags
    query = search_by_author(query, author)
    q.blank? ? query : omnisearch(query, q)
  end

  class << self
    private
    def search_by_tags(tags, query=nil)
      case tags
      when Array, ActiveRecord::Relation
        query = join
        tags.each {|tag| query = search_by_tags(tag, query)}
        query
      when Integer, Tag
        join.where tags: {id: tags}
      when NilClass
        Article.left_outer_joins(:author)
      else
        raise TypeError
      end
    end

    def join
      Article.includes(:tags).left_outer_joins(:author)
    end
    
    def omnisearch(query_chain, q)
      query_chain.where "title ilike :q or tldr ilike :q or body ilike :q", q: "%#{q}%"
    end

    def search_by_author(query_chain, author)
      case author
      when User
        query_chain.where author: author
      when String
        author.empty? ? query_chain : query_chain.where('users.handle = :author', author: author)
      when NilClass
        query_chain
      else
        raise TypeError
      end
    end
  end
end

app/controllers/articles_controller.rb
require 'concerns/permission'
require 'concerns/error_actions'

class ArticlesController < ApplicationController
  include Concerns::Permission
  include Concerns::ErrorActions
  include Concerns::Taggable

  before_action :set_and_authorize, only: %i[edit update destroy]
  before_action :authorize, only: %i[new create]
  before_action :set_article, only: :show

  def index
    @articles = find_articles.paginate(page: params[:page], per_page: 10)
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new article_params

    if @article.save
      redirect_to @article, flash: {green: 'Article was successfully created.'}
    else
      error @article.errors, :new
    end
  end

  def show
    @article.update views: @article.views.succ
  end

  def update
    if @article.update(article_params)
      redirect_to @article, flash: {green: 'Article was successfully updated.'}
    else
      error @article.errors, :edit
    end
  end

  def destroy
    if @article.destroy
      redirect_to articles_path, flash: {info: "Article successfully deleted."}
    else
      error @article.errors, @article
    end
  end
  
  private
  def find_articles
    Article.with_attached_tldr_image
      .includes(:tags, :author)
      .search(
        params[:q],
        tags: find_tags,
        author: find_author(params[:users])
      ).order(created_at: :desc)
  end

  def find_author(author)
    author.blank? ? nil : User.find(author)
  end

  def set_article
    @article = Article.find params[:id]
  end

  def article_params
    hash = params.require(:article).permit :title, :body, :tldr, :tldr_image, :anonymous
    hash[:author] = hash.delete(:anonymous) == '1' ? nil : current_user
    hash.merge tags: find_tags
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def author_label(article)
    author = article.author
    return anonymous_label if author.nil?
    return admin_label(author) if author.admin?
    regular_label(author)
  end

  private
  def anonymous_label
    content_tag(
      :label,
      ("by Anonymous " + content_tag(:i, nil, class: "user secret icon")).html_safe,
      class: "ui black label"
    )
  end

  def admin_label(author)
    link_to(
      ("by #{author.handle} " + content_tag(:i, nil, class: "shield alternate icon")).html_safe,
      user_path(author),
      class: "ui red label"
    )
  end

  def regular_label(author)
    link_to("by #{author.handle}", user_path(author), class: "ui label")
  end
end

app/views/articles/edit.html.erb
<h1>Edit article</h1>
<%= render 'articles/form/form', article: @article %>

app/views/articles/index.html.erb
<%= render 'articles/index/header' %>

<div class="ui stackable items">
  <%= render partial: "articles/index/article", collection: @articles %>
</div>

<div class="pagination">
  <%= will_paginate @articles %>
</div>

app/views/articles/new.html.erb
<h1>New Article</h1>
<%= render 'articles/form/form', article: @article %>

app/views/articles/show.html.erb
<%= content_tag :h1, @article.title %>

<%= content_tag :div, author_label(@article), class: "field" %>

<div class="grey">
  <div class="field">
    Created at <%= @article.created_at %>
  </div>

  <div class="field">
    View count: <%= @article.views %>
  </div>
</div>

<% if current_user&.has_permission? @article %>
  <% admin = current_user != @article.owner && current_user.admin? %>

  <div class="field">
    <%= link_to "Edit article#{' as admin' if admin}", edit_article_path(@article) %>
  </div>
  <div class="field">
    <%= link_to "Delete article#{' as admin' if admin}", article_path(@article), method: :delete %>
  </div>
<% end %>

<% unless @article.tags.empty? %>
  <div class="ui message">
    <h2>Tags</h2>
    <div class="ui list">
      <% @article.tags.find_each do |tag| %>
        <div class="item">
          <%= render "tags/tag", tag: tag %>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

<% tldr = @article.tldr %>
<% tldr_image = @article.tldr_image.attachment %>

<% unless tldr.nil? && tldr_image.nil? %>
  <div class="ui segment">
    <h2>tldr</h2>
    <%= tldr %>
    <% unless tldr_image.nil? %>
      <%= image_tag(@article.tldr_image.attachment, class: "image") %>
    <% end %>
  </div>
<% end %>

<%= @article.body.html_safe %>

<%= javascript_include_tag "import_katex_readonly" %>