config/routes.rb
Rails.application.routes.draw do
  get "logout" => "sessions#destroy"
  get "login" => "sessions#new"
  post "login" => "sessions#create"

  get 'edit-profile' => 'users#edit'
  delete 'delete' => 'users#destroy'
  patch 'update-profile' => 'users#update'

  resources :articles
  resources :tags, except: %i[show]
  resources :users, only: %i[index show] do
    member do
      patch 'verify' => 'users#verify'
    end
    collection do
      get 'change-password' => 'users#change_password'
      patch 'change-password' => 'users#update_password'
      get 'leaderboard' => 'users#leaderboard'
    end
  end

  get 'contact' => 'static#contact'
  get 'about' => 'static#about'
  get 'faqs' => 'static#faqs'
  get 'privacy' => 'static#privacy'
  root 'static#index'
end

app/models/user.rb
require 'user_validator'

class User < PermissionModel
  has_secure_password

  has_many :verifications_user
  has_many :tags, through: :verifications_user

  has_many :articles, foreign_key: :author_id, dependent: :nullify

  has_one_attached :profile_picture

  validates_with UserValidator
  
  validates :password,
            presence: true,
            length: {minimum: UserValidator::PW_MIN},
            format: {with: UserValidator::PW_REGEX,
                     message: "must contain a letter and a special character."},
            if: lambda {|user| user.new_record? || !user.password.blank?}

  validates :handle,
            presence: true,
            length: {in: UserValidator::HANDLE_MIN..UserValidator::HANDLE_MAX},
            uniqueness: true

  before_save do |record|
    record.handle.strip!
  end

  def self.by_popularity
    joins(:articles).group('users.id').order(Arel.sql('sum(articles.views) desc'))
  end
  
  def has_permission?(*models, &block)
    raise NoMethodError unless models.all? {|model| model.respond_to? :owner}
    has_access = self.admin? || models.all? {|model| model.owner == self}
    block_given? ? has_access && block.call : has_access
  end

  def owner
    self
  end
end

app/controllers/users_controller.rb
require 'concerns/permission'
require 'concerns/error_actions'
require 'concerns/taggable'

class UsersController < ApplicationController
  include Concerns::Permission
  include Concerns::ErrorActions
  include Concerns::Taggable

  before_action :authorize, only: %i[change_password update_password update destroy edit]
  before_action :mod_as_admin, only: %i[verify]

  UPDATE = 'User was successfully updated.'.freeze
  DELETE = "User successfully deleted.".freeze
  PW_CHANGED = "Successfully changed password.".freeze
  PW_MISMATCH = "New password and confirm password do not match".freeze
  ORIGINAL_PW_INCORRECT = "Current password was incorrect. Enter current password to change it to new password.".freeze

  LEADERBOARD_PER_PAGE = 25
  
  def index
    @users = User.all
  end

  def show
    @user = User.includes(:articles).find(params[:id])
  end
 
  def edit
  end

  def leaderboard
    @rank = current_rank
    @users = User.by_popularity.paginate(
      per_page: LEADERBOARD_PER_PAGE, page: params[:page]
    )
  end

  def verify
    if @user.update tags: find_tags
      redirect_to @user, flash: {green: "Verified #{@user.handle}."}
    else
      error @user.errors, :show
    end
  end
  
  def update
    if current_user.update(user_params)
      redirect_to current_user, flash: {green: UPDATE}
    else
      error current_user.errors, :edit
    end
  end

  def destroy
    if current_user.destroy
      redirect_to users_path, flash: {info: DELETE}
      reset_session
    else
      flash.now[:red] = current_user.errors
      redirect_to current_user
    end
  end

  def update_password
    if params[:new] == params[:confirm]
      change_password current_user.authenticate(params[:current])
    else
      error PW_MISMATCH, 'change_password'
    end
  end
  
  private
  def user_params
    params.require(:user).permit(:handle, :profile_picture)
  end

  def change_password(user)
    if user
      try_change_password user, params[:new]
    else
      error ORIGINAL_PW_INCORRECT, 'change_password'
    end
  end

  def try_change_password(user, new_pw)
    if user.update(password: new_pw)
      redirect_to user, flash: {info: PW_CHANGED}
    else
      error user.errors, 'change_password'
    end
  end

  def current_rank
    return 0 if params[:page].nil?
    LEADERBOARD_PER_PAGE * (params[:page].to_i - 1)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def leaderboard_crown(rank)
    case rank
    when 1
      number_one
    when 2
      second_place
    when 3
      third_place
    else
      content_tag(:h2, rank)
    end
  end

  private
  def number_one
    content_tag(
      :h2,
      ('1' + content_tag(:i, nil, class: 'chess king icon')).html_safe,
      class: 'gold'
    )
  end

  def second_place
    content_tag(
      :h2,
      ('2' + content_tag(:i, nil, class: 'chess queen icon')).html_safe,
      class: 'silver'
    )
  end

  def third_place
    content_tag(
      :h2,
      ('3' + content_tag(:i, nil, class: 'chess rook icon')).html_safe,
      class: 'bronze'
    )
  end
end

app/views/users/_dropdown.html.erb
<% users = local_assigns.fetch :users, User.select(:id, :handle, :admin).all %>
<% selected = local_assigns.fetch :selected, nil %>
<% multiple = local_assigns.fetch :multiple, false %>
<% selected = local_assigns.fetch :selected, nil %>

<%#================================================================%>

<%= render('shared/dropdown',
           multiple: multiple,
           options: users,
           name: 'users',
           default_text: 'Users',
           selected: selected) do |user| %>

  <div class="item" data-value="<%= user.id %>">
    <%= user.handle %>

    <% if user.admin? %>
      <i class="red shield alternate icon"></i>
    <% end %>
  </div>
  
<% end %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true, url: url, class: "ui form", method: method) do |f| %>  
  <div class="field">
    <%= f.label :profile_picture, "Profile picture", class: 'label' %>
    <%= f.file_field :profile_picture, accept: 'image/*' %>
  </div>

  <div class="field">
    <h3>Current profile picture</h3>
    <div class="large image">
      <%= image_tag(user.profile_picture.attachment) %>
    </div>
  </div>
  
  <div class="field">
    <%= f.label :handle, class: 'label' %>
    <%= f.text_field :handle %>
  </div> 

  <div class="actions">
    <%= f.submit "Submit", class: "ui primary button", id: "submit-user" %>
  </div>
<% end %>

app/views/users/change_password.html.erb
<h1>Change password</h1>

<p>
  New passwords need to:
  <ul>
    <li>Be at least <%= UserValidator::PW_MIN %> characters</li>
    <li>Be at most <%= UserValidator::PW_MAX %> characters</li>
    <li>Contain a letter</li>
    <li>Contain a number or one of these (preferrably one of these):</li>
    <ul>
      <li><%= UserValidator::PW_SPECIAL_CHARS %></li>
    </ul>
  </ul>
</p>

<%= form_tag change_password_users_path, method: :patch, class: "ui form", id: "pw-change" do %>
  <div class="field">
    <%= label_tag :current, "Current password", class: "label" %>
    <%= text_field_tag :current, nil, type: "password" %>
  </div>

  <div class="field" id="new-field">
    <%= label_tag :new, "New password", class: "label" %>
    <%= text_field_tag :new, nil, type: "password" %>
  </div>

  <div class="field" id="confirm-field">
    <%= label_tag :confirm, "Confirm new password", class: "label" %>
    <%= text_field_tag :confirm, nil, type: "password" %>
  </div>

  <div class="ui error message">
    <p>New password and password confirmation don't match yet</p>
  </div>

  <div class="actions">
    <%= submit_tag "Submit", class: "ui primary button", id: "submit" %>
  </div>
<% end %>

<%= javascript_include_tag "password_checks" %>

app/views/users/edit.html.erb
<h1>Edit profile</h1>

<%= render 'form', user: current_user, url: update_profile_path, method: :patch %>

app/views/users/index.html.erb
<h1>all users</h1>

<div class="ui stackable items">
  <%= render partial: 'users/index/user', collection: @users %>
</div>

app/views/users/leaderboard.html.erb
<h1>Leaderboards</h1>

<div class="ui stackable grid">
  <% @users.find_each do |user| %>
    <% @rank += 1 %>

    <div class="two wide middle aligned column">
      <%= leaderboard_crown(@rank) %>
    </div>

    <div class="fourteen wide column">
      <div class="ui basic segment">
        <div class="ui small image">
          <%= image_tag(user.profile_picture.attachment) %>
        </div>
        <div class="content">
          <%= link_to content_tag(:h3, user.handle), user, class: "header" %>

          <div class="extra">
            Views accumulated: <%= user.articles.sum(:views) %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div class="pagination">
  <%= will_paginate @users %>
</div>

app/views/users/show.html.erb
<div class="ui segment">
  <% if @user.tags.any? %>
    <%= render 'verifications_user/verified_rail', tags: @user.tags %>
  <% end %>

  <% if current_user&.admin? %>
    <%= render 'verifications_user/verify_user_rail', tags: @user.tags %>
  <% end %>

  <div class="ui stackable items">
    <div class="item" id="<%= dom_id(@user) %>">

      <div class="ui medium image">
        <%= image_tag(@user.profile_picture.attachment) %>
      </div>

      <div class="content">
        <%= content_tag :h4, @user.handle, class: "header" %>

        <div class="meta">
          <% if @user.admin? %>
            <label class="ui red label">
              Administrator <i class="shield alterate icon"></i>
            </label>
          <% end %>
        </div>

        <div class="extra">
          Joined: <%= @user.created_at %>
        </div>

        <div class="extra">
          Articles written: <%= Article.where(author: @user).count %>
        </div>

        <% if current_user == @user %>
          <a class="extra" href="<%= delete_path %>" data-confirm="Are you sure?" data-method="delete">
            <i class="red trash icon"></i> Delete account
          </a>
        <% end %>
      </div>
    </div>
  </div>
</div>

<h1>Recent activity</h1>

<div class="ui stackable items">
  <%= render partial: "articles/index/article", collection: @user.articles.last(5) %>
</div>