config/routes.rb
Rails.application.routes.draw do
  get "logout" => "sessions#destroy"
  get "login" => "sessions#new"
  post "login" => "sessions#create"

  get 'edit-profile' => 'users#edit'
  delete 'delete' => 'users#destroy'
  patch 'update-profile' => 'users#update'

  resources :articles
  resources :tags, except: %i[show]
  resources :users, only: %i[index show] do
    member do
      patch 'verify' => 'users#verify'
    end
    collection do
      get 'change-password' => 'users#change_password'
      patch 'change-password' => 'users#update_password'
      get 'leaderboard' => 'users#leaderboard'
    end
  end

  get 'contact' => 'static#contact'
  get 'about' => 'static#about'
  get 'faqs' => 'static#faqs'
  get 'privacy' => 'static#privacy'
  root 'static#index'
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :articles_tag, dependent: :destroy
  has_many :articles, through: :articles_tag
  belongs_to :semantic_ui_icon

  NAME_MIN = 3
  NAME_MAX = 64

  COLOR_MIN = 3
  COLOR_MAX = 7
  COLOR_REGEX = /\A[#]{0,1}([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})\z/i

  validates :color,
            allow_nil: true,
            format: {with: COLOR_REGEX},
            length: {minimum: COLOR_MIN, maximum: COLOR_MAX}

  validates :name,
            presence: true,
            uniqueness: {case_sensitive: false},
            length: {minimum: NAME_MIN, maximum: NAME_MAX}

  alias_method :icon, :semantic_ui_icon

  before_save do |tag|
    tag.name.downcase!
    tag.color = tag.color.downcase.sub('#','') if tag.color
  end
end

app/controllers/tags_controller.rb
require 'concerns/permission'
require 'concerns/error_actions'

class TagsController < ApplicationController
  include Concerns::Permission
  include Concerns::ErrorActions

  before_action :admin_only, except: :index
  before_action :set_tag, only: %i[edit update destroy]

  def index
    @tags = Tag.all.paginate(page: params[:page], per_page: 25)
  end

  def edit
  end

  def create
    tag = Tag.new tag_params

    if tag.save
      redirect_to tags_path, flash: {green: 'Tag successfully created.'}
    else
      error tag.errors, :new
    end
  end

  def update
    if @tag.update tag_params
      redirect_to tags_path, flash: {green: 'Tag successfully updated.'}
    else
      error @tag.errors, :edit
    end
  end

  def destroy
    if @tag.destroy
      redirect_to tags_path, flash: {info: 'Tag successfully deleted.'}
    else
      error @tag.errors, :index
    end
  end

  private
  def set_tag
    @tag = Tag.find params[:id]
  end

  def tag_params
    hash = params.require(:tag).permit :name, :color
    hash.merge semantic_ui_icon_id: params[:semantic_ui_icons]
  end
end

app/helpers/tags_helper.rb
module TagsHelper
  def tag_icon(tag, size: nil)
    color = "color: ##{tag.color}"
    klass = "#{size} #{tag.icon.icon} icon"
    content_tag(:i, nil, class: klass, style: color)
  end

  private
  def find_id(arg)
    case arg
    when String
      Tag.select(:id).where('name = ?', arg).limit(1).pluck(:id).first
    when Tag
      arg.id
    else
      raise TypeError, "Can't find the ID from #{arg.class}"
    end
  end
end

app/views/tags/_dropdown.html.erb
<% tags = local_assigns.fetch :tags, Tag.includes(:semantic_ui_icon).all %>
<% selected = local_assigns.fetch :selected, nil %>
<% multiple = local_assigns.fetch :multiple, false %>
<% selected = local_assigns.fetch :selected, nil %>

<%# =================================================================== %>

<%= render('shared/dropdown',
           multiple: multiple,
           options: tags,
           name: 'tags',
           default_text: 'Tags',
           selected: selected) do |tag| %>

  <div class="item" data-value="<%= tag.id %>">
    <%= tag_icon tag %>
    <%= tag.name.capitalize %>
  </div>

<% end %>

app/views/tags/_form.html.erb
<%= form_with(model: tag, local: true, url: url, class: "ui form", method: method) do |f| %>  
  <div class="field">
    <%= f.label :name, class: 'label' %>
    <%= f.text_field :name, maxlength: Tag::NAME_MAX %>
  </div>

  <div class="field">
    <%= f.label :semantic_ui_icon_id, class: 'label' %>
    <%= render('semantic_ui_icons/dropdown', selected: tag.semantic_ui_icon) %>
  </div>

  <div class="field">
    <%= f.label :color, class: 'label' %>
    <%= f.text_field :color, id: 'color' %>
  </div> 

  <div class="actions">
    <%= f.submit "Submit", class: "ui primary button", id: "submit-user" %>
  </div>
<% end %>

<script>
 $('#color').minicolors({inline: true})
</script>

app/views/tags/_tag.html.erb
<a href="/articles?tags=<%= tag.id %>" class="ui label">
  <%= tag_icon tag %>  
  <%= tag.name.capitalize %>
</a>

app/views/tags/edit.html.erb
<h1>Edit tag</h1>
<%= render 'form', tag: @tag, url: @tag, method: :patch %>

app/views/tags/index.html.erb
<h1>All tags</h1>

<% admin = current_user&.admin? %>

<% if admin %>
  <% trash = content_tag(:i, nil, class: 'red trash alternate icon') %>

  <a class="ui green basic animated button" href="<%= new_tag_path %>" tabindex="0">
    <div class="visible content">New tag</div>
    <div class="hidden content">
      <i class="plus icon"></i>
    </div>
  </a>
<% end %>

<table class="table">
  <tbody>
    <% @tags.each do |tag| %>
      <tr>
        <td style="padding: 10px">
          <%= tag_icon tag, size: "huge" %>
        </td>
        <td style="padding: 10px">
          <%= content_tag :h3, tag.name %>
        </td>
        <td style="padding: 10px">
          <%= content_tag :h3, "##{tag.color}" %>
        </td>

        <% if admin %>
          <td>
            <%= link_to "Edit", edit_tag_path(tag) %>
            <%= link_to trash, tag_path(tag), method: :delete, 'data-confirm' => "You sure?" %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="pagination">
  <%= will_paginate @articles %>
</div>

app/views/tags/new.html.erb
<h1>New tag</h1>
<%= render 'form', tag: Tag.new, url: tags_path, method: :post %>