config/routes.rb
Rails.application.routes.draw do
  get "logout" => "sessions#destroy"
  get "login" => "sessions#new"
  post "login" => "sessions#create"

  get 'edit-profile' => 'users#edit'
  delete 'delete' => 'users#destroy'
  patch 'update-profile' => 'users#update'

  resources :articles
  resources :tags, except: %i[show]
  resources :users, only: %i[index show] do
    member do
      patch 'verify' => 'users#verify'
    end
    collection do
      get 'change-password' => 'users#change_password'
      patch 'change-password' => 'users#update_password'
      get 'leaderboard' => 'users#leaderboard'
    end
  end

  get 'contact' => 'static#contact'
  get 'about' => 'static#about'
  get 'faqs' => 'static#faqs'
  get 'privacy' => 'static#privacy'
  root 'static#index'
end

app/views/layouts/_flash.html.erb
<% flash.each do |type, message| %>
  <div class="ui <%= type %> message" id="flash">
    <% if message.instance_of? ActiveModel::Errors %>
      Error while trying to save:
      <ul>
        <% message.full_messages.each do |message| %>
          <%= content_tag :li, message %>
        <% end %>
      </ul>
    <% else %>
      <%= message %>
    <% end %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<div class="ui inverted vertical footer segment flex-wrapper" id="footer">
  <div class="ui container">
    <div class="ui stackable inverted divided equal height stackable grid">
      <div class="five wide column">
        <h4 class="inverted">Information</h4>
        <div class="ui inverted link list">
          <%= link_to "About", about_path, class: "item" %>
          <%= link_to "FAQs", faqs_path, class: "item" %>
          <%= link_to "Contact", contact_path, class: "item" %>
          <%= link_to "Privacy", privacy_path, class: "item" %>
        </div>
      </div>
      <div class="six wide column">
        <h4 class="inverted">Users</h4>
        <div class="ui inverted link list">
          <%= link_to "All", users_path, class: "item" %>
          <%= link_to "Leaderboard", leaderboard_users_path, class: "item" %>

          <% most_poppin_user = most_popular_user %>
          <% unless most_poppin_user.nil? %>
            <%= link_to "Most popular user right now", most_popular_user, class: "item" %>
          <% end %>
        </div>
      </div>
      <div class="five wide column">
        <h4 class="inverted">Tags</h4>
        <div class="ui inverted link list">
          <%= link_to "All", tags_path, class: "item" %>
          <%= link_to("New", new_tag_path, class: "item") if current_user&.admin? %>
        </div>
      </div>
    </div>
    <div class="ui one column stackable center aligned page grid">
      <div class="twelve wide column">
        <%= image_tag "sudobangbang_green.gif", height: 50, width: 200 %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<div class="ui secondary menu">

  <div class="item">
    <%= link_to image_tag("sudobangbang_white.gif", width: 100, height: 25), root_path %>
  </div>

  <div class="ui pointing dropdown link item">
    <span class="text">Articles</span>
    <i class="dropdown icon"></i>
    <div class="menu">
      <%= link_to "All", articles_path, class: "item" %>
      <%= link_to "New", new_article_path, class: "item" %>
    </div>
  </div>

  <div class="right menu">
    <% if current_user.nil? %>
      <%= link_to "Log in", login_path, class: "item" %>
    <% else %>
      <div class="ui pointing dropdown link item">
        <span class="text"><%= current_user.handle %></span>
        <i class="dropdown icon"></i>
        <div class="menu">
          <%= link_to "Edit profile", edit_profile_path, class: "item" %>
          <%= link_to "View profile", user_path(current_user), class: "item" %>
          <%= link_to "Change password", change_password_users_path, class: "item" %>
          <%= link_to "Log out", logout_path, class: "item" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>sudo !!</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%# Highlight JS %>
    <!--
    <link rel="stylesheet" href="/path/to/styles/default.css">
    <script src="/path/to/highlight.pack.js"></script>
    <script>hljs.initHighlightingOnLoad();</script>
    -->
    <%# CKEditor %>
    <script src="https://cdn.ckeditor.com/ckeditor5/11.2.0/classic/ckeditor.js" crossorigin="anonymous"></script>

    <%# Katex %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.11.0/dist/katex.min.css" integrity="sha384-BdGj8xC2eZkQaxoQ8nSLefg4AV4/AwB3Fj+8SUSo7pnKP6Eoy18liIKTPn9oBYNG" crossorigin="anonymous">
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.11.0/dist/katex.min.js" integrity="sha384-JiKN5O8x9Hhs/UE5cT5AAJqieYlOZbGT3CHws/y97o3ty4R7/O5poG9F3JoiOYw1" crossorigin="anonymous"></script>
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.11.0/dist/contrib/auto-render.min.js" integrity="sha384-kWPLUVMOks5AQFrykwIup5lo0m3iMkkHrD0uJ4H5cjeGihAutqP0yW0J6dpFiVkI" crossorigin="anonymous"></script>

    <%# Font awesome %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="ui container" id="main">
      <%= render "layouts/flash" %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>